### ISSUE TITLE
Referrer Bug

### ISSUE THREAD

**Issue by Der---Flo** [MacLeanElectrical/servicestack-authentication-identityserver#1]
In sample ServiceAuthProvider.ServiceStack.SelfHostThrows an NullException Error is thown, when accessing "http://localhost:5001/hello/" direktly (over the adress bar, not over the link).

**Comment by Der---Flo** [comment]
Suggested fix:

UserAuthProvider:

        internal bool IsCallbackRequest(IServiceBase authService, Authenticate request)
        {
            var httpRequest = authService.Request;
            if (string.IsNullOrEmpty(httpRequest.AbsoluteUri))
            {
                return false;
            }

            if (httpRequest.AbsoluteUri.IndexOf(CallbackUrl, StringComparison.InvariantCultureIgnoreCase) != 0)
            {
                return false;
            }

            var referer = GetReferrerUrl(authService, authService.GetSession(), request);
            return referer != null && referer.IndexOf(AuthRealm, StringComparison.InvariantCultureIgnoreCase) == 0;
        }

**Comment by stuartbfs** [comment]
Thanks for pointing this out @Der---Flo. Applied bug fix as per your suggestion - [commit](https://github.com/MacLeanElectrical/servicestack-authentication-identityserver/commit/381b3a9d944befecc781372a7bd94c45fda1111f)
